nube/nube/urls.py
from django.contrib import admin
from django.urls import path
from .views import*
import re
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include

from ninja import NinjaAPI
from prueba.api import router as api_router
from pasteleria.api import router as api_router
from pizzeria.api import router as api_router
api= NinjaAPI()
api.add_router("/api/",api_router)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',entrada, name="entrada"),
    path('hijo/',hijo, name="hijo"),
    url(r'^', include('prueba.urls')),
    url(r'^', include('pizzeria.urls')),
    url(r'^', include('pasteleria.urls')),
    #path("api/",api.urls),
]


#if settings.MEDIA_URL.startswith("/"):
#   urlpatterns += [
 #       url(
  #          r'^{MEDIA_URL}(?P<path>.*)$'.format(MEDIA_URL=re.escape(settings.MEDIA_URL.lstrip('/'))),
   #         serve,
    #        {'document_root': settings.MEDIA_ROOT},
     #   ),
    #]
if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT
    )

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nube/pizzeria/models.py
from django.db import models
from  django.conf import settings


# Create your models here.
class pizza(models.Model):
    tipopizza=models.CharField(max_length=20, blank=True, null=True)
    tamano= models.CharField(max_length=20, blank=True, null=True)
    #extras= models.IntegerField(max_length=20, blank=True, null=True)
    precio=models.CharField(max_length=20, blank=True, null=True)

nube/templates/pizza/actualizarpizza.html
{% extends "base.html" %} {% block content %} {{ dato.color}}
<form method="post" enctype="multipart/form-data">
  <style type="text/css">
    body {
      padding-left: 11em;
      font-family: Georgia, "Times New Roman", Times, serif;
      color: purple;
      background-color: #ffe4c4;
    }
    ul.navbar {
      list-style-type: none;
      padding: 0;
      margin: 0;
      position: absolute;
      top: 2em;
      left: 1em;
      width: 9em;
    }
    h1 {
      font-family: Helvetica, Geneva, Arial, SunSans-Regular, sans-serif;
    }
    ul.navbar li {
      background: white;
      margin: 0.5em 0;
      padding: 0.3em;
      border-right: 1em solid black;
    }
    ul.navbar a {
      text-decoration: none;
    }
    a:link {
      color: blue;
    }
    a:visited {
      color: purple;
    }

    table {
      width: 100%;
      text-align: left;
      border-collapse: collapse;
      margin: 0 0 1em 0;
      caption-side: top;
    }
    caption,
    td,
    th {
      padding: 0.3em;
    }
    tbody {
      border-top: 1px solid #000;
      border-bottom: 1px solid #000;
    }
    tbody th,
    tfoot th {
      border: 0;
    }
    th.name {
      width: 25%;
    }
    th.location {
      width: 20%;
    }
    th.lasteruption {
      width: 30%;
    }
    th.eruptiontype {
      width: 25%;
    }
    tfoot {
      text-align: center;
      color: #555;
      font-size: 0.8em;
    }
  </style>
  {% csrf_token %}
  <p>
    <label for="id_tipopizza">Pizza::</label>
    <input
      type="text"
      name="tipopizza"
      maxlength="20"
      id="id_tipopizza"
      value="{{dato.tipopizza}}"
    />
  </p>
  <p>
    <label for="id_tamano">Tamaño:</label>
    <input
      type="text"
      name="tamano"
      maxlength="20"
      id="id_tamano"
      value="{{dato.tamano}}"
    />
  </p>
  <p>
    <label for="id_precio">Precio:</label>
    <input
      type="number"
      name="precio"
      required=""
      id="id_precio"
      value="{{dato.precio}}"
    />
  </p>
  <button type="submit" class="btn btn-primary">Actualizar</button>
</form>
{% endblock content %}

nube/templates/pizza/agregarpizza.html
{% extends "base.html" %} {% block content %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}

  <button type="submit" class="btn btn-primary">Aceptar</button>
</form>
{% endblock content %}

nube/templates/pizza/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    {% block title %}
    <title>Servicios en la nube</title>
    {% endblock title %}

    <style></style>
  </head>
  <body>
    <header></header>

    <main>{% block content %} {% endblock content%}</main>

    <script type="text/javascript"></script>
    {% block js %} {% endblock js %}

    <footer></footer>
  </body>
</html>

nube/templates/pizza/listarpizza.html
{% extends "base.html" %} {% block content %}

<button onclick="location.href='/pizzas/crear'">agregar</button>
<style type="text/css">
  body {
    padding-left: 11em;
    font-family: Georgia, "Times New Roman", Times, serif;
    color: purple;
    background-color: #ffe4c4;
  }
  ul.navbar {
    list-style-type: none;
    padding: 0;
    margin: 0;
    position: absolute;
    top: 2em;
    left: 1em;
    width: 9em;
  }
  h1 {
    font-family: Helvetica, Geneva, Arial, SunSans-Regular, sans-serif;
  }
  ul.navbar li {
    background: white;
    margin: 0.5em 0;
    padding: 0.3em;
    border-right: 1em solid black;
  }
  ul.navbar a {
    text-decoration: none;
  }
  a:link {
    color: blue;
  }
  a:visited {
    color: purple;
  }

  table {
    width: 100%;
    text-align: left;
    border-collapse: collapse;
    margin: 0 0 1em 0;
    caption-side: top;
  }
  caption,
  td,
  th {
    padding: 0.3em;
  }
  tbody {
    border-top: 1px solid #000;
    border-bottom: 1px solid #000;
  }
  tbody th,
  tfoot th {
    border: 0;
  }
  th.name {
    width: 25%;
  }
  th.location {
    width: 20%;
  }
  th.lasteruption {
    width: 30%;
  }
  th.eruptiontype {
    width: 25%;
  }
  tfoot {
    text-align: center;
    color: #555;
    font-size: 0.8em;
  }
</style>
<table>
  <tr>
    <th>Pizza</th>
    <th>Tamaño</th>
    <th>Precio</th>
  </tr>
  {% for n in pizza %}
  <tr>
    <td>{{n.tipopizza}}</td>
    <td>{{n.tamano}}</td>
    <td>{{n.precio}}</td>
    <br />
    <td>
      <button id="{{n.id}}" onclick="location.href='/actualizarpizza/{{n.id}}'">
        actualizar
      </button>
    </td>
    <td>
      <button id="{{n.id}}" onclick="location.href='/eliminarpizza/{{n.id}}'">
        eliminar
      </button>
    </td>
  </tr>
</table>
{% endfor %} {% endblock content %}

nube/templates/pizza/templ1.html
{% extends "base.html" %}
{% block content %}
<p>hola soy el hijo que hereda</p><p>hola soy el hijo que hereda</p>
{% endblock content %}