nube/nube/urls.py
from django.contrib import admin
from django.urls import path
from .views import*
import re
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include

from ninja import NinjaAPI
from prueba.api import router as api_router
from pasteleria.api import router as api_router
from pizzeria.api import router as api_router
api= NinjaAPI()
api.add_router("/api/",api_router)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',entrada, name="entrada"),
    path('hijo/',hijo, name="hijo"),
    url(r'^', include('prueba.urls')),
    url(r'^', include('pizzeria.urls')),
    url(r'^', include('pasteleria.urls')),
    #path("api/",api.urls),
]


#if settings.MEDIA_URL.startswith("/"):
#   urlpatterns += [
 #       url(
  #          r'^{MEDIA_URL}(?P<path>.*)$'.format(MEDIA_URL=re.escape(settings.MEDIA_URL.lstrip('/'))),
   #         serve,
    #        {'document_root': settings.MEDIA_ROOT},
     #   ),
    #]
if settings.DEBUG: 
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root = settings.MEDIA_ROOT
    )

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nube/pasteleria/urls.py
from django.contrib import admin
from django.urls import path
#from .views import*
import re
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from .views import *


urlpatterns = [
    path('pasteleria/listar/',listar,name="pasteleria/listar/"),
     path('pasteleria/crearpastel/', crearpastel, name='crearpastel/'),
    path('eliminarpastel/<int:id>',eliminarpastel,name='eliminarpastel'),
    path('actualizarpastel/<int:id>',actualizarpastel,name='actualizarpastel/'),
]

nube/pasteleria/models.py
from django.db import models
from  django.conf import settings



# Create your models here.
class pasteleria(models.Model):
    #tipopastel = models.CharField(max_length=20, help_text="Enter field documentation")
    tipopastel=models.CharField(max_length=20, blank=True, null=True)
    tamano= models.CharField(max_length=20, blank=True, null=True)
    #Descripcion= models.IntegerField(max_length=20, blank=True, null=True)
    precio=models.CharField(max_length=20, blank=True, null=True)

nube/pasteleria/forms.py
from multiprocessing.sharedctypes import Value
from urllib import request
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class agregar(forms.ModelForm):
	class Meta:
		model=pasteleria
		fields= ['id','tipopastel','tamano','precio']

nube/pasteleria/views.py
from multiprocessing import context
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template import RequestContext
from django.urls import reverse
from django.views.generic import TemplateView
from django.contrib.auth import authenticate,login,logout
from pasteleria.models import *
from pasteleria.forms import agregar
from prueba.models import *

def entrada(request):
    template="base.html"
    return render(request, template)

def hijo(request):
    templatesPasteleria="templ1.html"
    return render(request,  templatesPasteleria)

# Crea tus vistas aquí.
def listar(request):
    pasteleria1= pasteleria.objects.all()
    template="pasteleria/lista.html"
    context={
        'pasteleria': pasteleria1,

    }
    return render (request,template,context)

def crearpastel(request): 
    if request.method=='POST':
        form= agregar(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/pasteleria/listar/')

    form = agregar 
    context={
        'form':form,

    }
    return render (request, "pasteleria/agregar.html", context)

def eliminarpastel(request, id):
    member= pasteleria.objects.get(id=id)
    member.delete()
    return redirect('pasteleria/listar/')

def actualizarpastel(request,id):
    if request.method=='POST':
        instance=pasteleria.objects.get(id=id)
        form=agregar(request.POST or None, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('pasteleria/listar/')
    
    dato = pasteleria.objects.get(id=id)
    template = 'pasteleria/actualizar.html'
    context = {
    'dato': dato,
    }
    return render(request, template, context)

  
  
  

nube/templates/pasteleria/actualizar.html
{% extends "base.html" %} {% block content %} {{ dato.color}}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <p>
    <style type="text/css">
      body {
        padding-left: 11em;
        font-family: Georgia, "Times New Roman", Times, serif;
        color: purple;
        background-color: #ffe4c4;
      }
      ul.navbar {
        list-style-type: none;
        padding: 0;
        margin: 0;
        position: absolute;
        top: 2em;
        left: 1em;
        width: 9em;
      }
      h1 {
        font-family: Helvetica, Geneva, Arial, SunSans-Regular, sans-serif;
      }
      ul.navbar li {
        background: white;
        margin: 0.5em 0;
        padding: 0.3em;
        border-right: 1em solid black;
      }
      ul.navbar a {
        text-decoration: none;
      }
      a:link {
        color: blue;
      }
      a:visited {
        color: purple;
      }

      table {
        width: 100%;
        text-align: left;
        border-collapse: collapse;
        margin: 0 0 1em 0;
        caption-side: top;
      }
      caption,
      td,
      th {
        padding: 0.3em;
      }
      tbody {
        border-top: 1px solid #000;
        border-bottom: 1px solid #000;
      }
      tbody th,
      tfoot th {
        border: 0;
      }
      th.name {
        width: 25%;
      }
      th.location {
        width: 20%;
      }
      th.lasteruption {
        width: 30%;
      }
      th.eruptiontype {
        width: 25%;
      }
      tfoot {
        text-align: center;
        color: #555;
        font-size: 0.8em;
      }
    </style>
    <label for="id_tipopastel">sabor pastel:</label>
    <input
      type="text"
      name="tipopastel"
      maxlength="20"
      id="id_tipopastel"
      value="{{dato.tipopastel}}"
    />
  </p>
  <p>
    <label for="id_tamano">tamano:</label>
    <input
      type="text"
      name="tamano"
      maxlength="20"
      id="id_tamano"
      value="{{dato.tamano}}"
    />
  </p>
  <p>
    <label for="id_precio">precio:</label>
    <input
      type="text"
      name="precio"
      maxlength="20"
      id="id_precio"
      value="{{dato.precio}}"
    />
  </p>

  <button type="submit" class="btn btn-primary">Actualizar</button>
</form>
{% endblock content %}

nube/templates/pasteleria/agregar.html
{% extends "base.html" %} {% block content %}
<form method="post" enctype="multipart/form-data">
  <style type="text/css">
    body {
      padding-left: 11em;
      font-family: Georgia, "Times New Roman", Times, serif;
      color: purple;
      background-color: #ffe4c4;
    }
    ul.navbar {
      list-style-type: none;
      padding: 0;
      margin: 0;
      position: absolute;
      top: 2em;
      left: 1em;
      width: 9em;
    }
    h1 {
      font-family: Helvetica, Geneva, Arial, SunSans-Regular, sans-serif;
    }
    ul.navbar li {
      background: white;
      margin: 0.5em 0;
      padding: 0.3em;
      border-right: 1em solid black;
    }
    ul.navbar a {
      text-decoration: none;
    }
    a:link {
      color: blue;
    }
    a:visited {
      color: purple;
    }

    table {
      width: 100%;
      text-align: left;
      border-collapse: collapse;
      margin: 0 0 1em 0;
      caption-side: top;
    }
    caption,
    td,
    th {
      padding: 0.3em;
    }
    tbody {
      border-top: 1px solid #000;
      border-bottom: 1px solid #000;
    }
    tbody th,
    tfoot th {
      border: 0;
    }
    th.name {
      width: 25%;
    }
    th.location {
      width: 20%;
    }
    th.lasteruption {
      width: 30%;
    }
    th.eruptiontype {
      width: 25%;
    }
    tfoot {
      text-align: center;
      color: #555;
      font-size: 0.8em;
    }
  </style>
  {% csrf_token %} {{ form.as_p }}

  <button type="submit" class="btn btn-primary">Aceptar</button>
</form>
{% endblock content %}

nube/templates/pasteleria/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	{% block title %}<title>Servicios en la nube</title> {% endblock title %}
    <p>hola soy padre</p>
	<p>hola soy padre</p>

    <style>



    </style>


    
</head>
<body>
    <header></header>

<main>

	{% block content %}
	{% endblock content%}

</main>




	<script type="text/javascript">



	</script>
	{% block js %}
	{% endblock js %}

<footer>

</footer>

</body>
</html>

nube/templates/pasteleria/lista.html
{% extends "base.html" %} {% block content %}
<style type="text/css">
  body {
    padding-left: 11em;
    font-family: Georgia, "Times New Roman", Times, serif;
    color: purple;
    background-color: #ffe4c4;
  }
  ul.navbar {
    list-style-type: none;
    padding: 0;
    margin: 0;
    position: absolute;
    top: 2em;
    left: 1em;
    width: 9em;
  }
  h1 {
    font-family: Helvetica, Geneva, Arial, SunSans-Regular, sans-serif;
  }
  ul.navbar li {
    background: white;
    margin: 0.5em 0;
    padding: 0.3em;
    border-right: 1em solid black;
  }
  ul.navbar a {
    text-decoration: none;
  }
  a:link {
    color: blue;
  }
  a:visited {
    color: purple;
  }

  table {
    width: 100%;
    text-align: left;
    border-collapse: collapse;
    margin: 0 0 1em 0;
    caption-side: top;
  }
  caption,
  td,
  th {
    padding: 0.3em;
  }
  tbody {
    border-top: 1px solid #000;
    border-bottom: 1px solid #000;
  }
  tbody th,
  tfoot th {
    border: 0;
  }
  th.name {
    width: 25%;
  }
  th.location {
    width: 20%;
  }
  th.lasteruption {
    width: 30%;
  }
  th.eruptiontype {
    width: 25%;
  }
  tfoot {
    text-align: center;
    color: #555;
    font-size: 0.8em;
  }
</style>
<button onclick="location.href='/pasteleria/crearpastel/'">agregar</button>

<table>
  <tr>
    <th>pastel</th>
    <th>tamano</th>
    <th>precio</th>
  </tr>
  {% for n in pasteleria %}
  <tr>
    <td>{{n.tipopastel}}</td>
    <td>{{n.tamano}}</td>
    <td>{{n.precio}}</td>
    <td>
      <button
        id="{{n.id}}"
        onclick="location.href='/actualizarpastel/{{n.id}}'"
      >
        actualizar
      </button>
    </td>
    <td>
      <button id="{{n.id}}" onclick="location.href='/eliminarpastel/{{n.id}}'">
        eliminar
      </button>
    </td>
  </tr>
</table>

{% endfor %} {% endblock content %}

nube/templates/pasteleria/templ1.html
{% extends "base.html" %}
{% block content %}
<p>hola soy el hijo que hereda</p><p>hola soy el hijo que hereda</p>
{% endblock content %}